server:
  port: 9000
  servlet:
    context-path: /
spring:
  application:
    name: ribbon-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka.node1:7005/eureka,http://eureka.node2:7006/eureka,http://eureka.node3:7007/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 30
