spring:
  profiles: 7008
  application:
    name: eureka-cluster-center
server:
  port: 7008
eureka:
  instance:
    hostname: eureka.node1
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://eureka.node2:7009/eureka/