# 应用服务名
spring:
  application:
    name: config-server
  profiles: native # 加载本地配置
  cloud:
    config:
      server:
        native:
          search-locations: /E:/gw/work/workspace/TLMS/branches/184/plate-cloud-system/cloud-system/config-system/config-server/resources/

server:
  port: 9096
eureka:
  instance:
    hostname: eureka.config.com
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://10.4.3.120:7005/eureka/,http://10.4.3.121:7006/eureka/,http://10.4.3.122:7007/eureka/
