# 应用服务名
spring:
   application:
     name: config-server
   cloud:
     config:
       server:
         git:
           uri: https://github.com/gaowei0115/cloud-config.git
           username: gao_wei0115@sina.com
           password: gaowei631890642
           search-paths: /config/${APP_LOCATE:dev}
     consul:
       host: localhost
       port: 8500
       discovery:
         ip-address: localhost
         port: ${server.port}
         instance-id: config-server-${server.port}
         service-name: config-server
server:
  port: 9096

logging:
  level:
    root: debug