# 应用服务名
spring:
  application:
    name: config-server

server:
  port: 9096
eureka:
  instance:
    hostname: eureka.config.com
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:7005/eureka/
